[nginx]
nginx-server ansible_host=nginx-server

[app]
app-server ansible_host=app-server

[all:vars]
ansible_connection=ssh
ansible_ssh_user=admin
ansible_ssh_pass=admin123
ansible_become_pass=admin123
ansible_python_interpreter=/usr/bin/python3